[package]
name = "metalink"
version = "0.1.0"
edition = "2021"
description = "Provides a parser for metalinks as defined in RFC5854"
license = "MIT"
repository = "https://github.com/engelphi/metalink-downloader"
readme = "README.md"
keywords = ["metalink", "RFC5854", "deserialization"]
categories = ["parsing", "parser-implementations", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iana-registry-enums = { path = "../iana-registry-enums" }
quick-xml = { version = "0.37.5", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
url = { version = "2.5.4", features = ["serde"] }
validator = { version = "0.20.0", features = ["derive"] }
chrono = { version = "0.4.41", features = ["serde"] }
mime = "0.3.17"
serde_with = "3.12.0"
thiserror = "2.0.12"
anyhow = "1.0.98"
isocountry = "0.3.2"

[dev-dependencies]
clap = { version = "4.5.37", features = ["derive"] }
